---
apiVersion: v1
kind: Namespace
metadata:
  name: web-npv
---
apiVersion: v1
kind: Service
metadata:
  name: web-npv-service
  namespace: web-npv
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web-npv
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80

